### ISSUE TITLE
Provide an HTTP header for a stream

### ISSUE THREAD

**Issue by TheBeastLT** [Stremio/stremio-addon-sdk#55] opened 2019-03-04 09:52 UTC
Is it possible to provide an http header for a stream, so that when accessing the stream the header would be attached to the request? Some of the streams require a header `Referer` to be attached in order to be able to access the stream.

**Comment by Ivshti** [comment] 2019-03-05 15:24
Currently, this is not possible, cause we're trying to design the streams object in a way that allows easy browser support (HTTPS/WebTorrent)

However, we can implement this feature in a relatively platform-agnostic way, but the problem is, the moment you use headers, browser users would need to connect their stremio to a streaming server (that will act as a proxy) in order to play those streams

in any case, we will consider this feature

**Comment by jaruba** [comment] 2022-02-04 10:11
Please see the [Stream Response](https://github.com/Stremio/stremio-addon-sdk/blob/master/docs/api/responses/stream.md) docs under `stream.behaviorHints.proxyHeaders`, this is available in both Desktop and Android versions.

**Comment by sleeyax** [comment] 2022-02-04 10:48
Can we close this issue now that we have the `proxyHeaders` option ?

**Comment by jaruba** [comment] 2022-02-04 10:56
@sleeyax yup

**Closed by jaruba** 2022-02-04 10:56 UTC

**Comment by zoreu** [comment] 2022-12-31 20:07
this json is not working :

{"streams":[{"proxyHeaders":{"request":{"Referer":"[https://myreferer.com/"}},"title](https://myreferer.com/%22%7D%7D,%22title)":" VIDEO HD (HTTP)","url":"[https://mysite.com/video.mp4"}]}](https://mysite.com/video.mp4%22%7D]%7D)

**Comment by jaruba** [comment] 2022-12-31 20:24
@zoreu because it is wrong, follow the stream object definition precisely:
```json
{
  streams: [
    {
      url: "...",
      title: "...",
      behaviorHints: {
        proxyHeaders: {
          // ...
        },
      }
   ]
}
```

**Comment by zoreu** [comment] 2022-12-31 20:48
> {"request": {"Referer": "http://myreferer.com" } }

still not opened the transmission, did I do it right? does stremio support this? I have the last version

`{"streams":[{"behaviorHints":{"proxyHeaders":{"request":{"Referer":"https://referer.com/","User-Agent":"Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Mobile Safari/537.36"}}},"title":"ASSISTIR","url":"https://site.com/channel/playlist.m3u8"}]}`

**Comment by zoreu** [comment] 2022-12-31 20:59
> @zoreu because it is wrong, follow the stream object definition precisely:
> 
> ```json
> {
>   "streams": [
>     {
>       "url": "...",
>       "title": "...",
>       "behaviorHints": {
>         "proxyHeaders": {
>           // ...
>         },
>       }
>    }
> ]
> ```

still not opened the transmission, did I do it right? does stremio support this? I have the last version

`{"streams":[{"behaviorHints":{"proxyHeaders":{"request":{"Referer":"https://referer.com/","User-Agent":"Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Mobile Safari/537.36"}}},"title":"ASSISTIR","url":"https://site.com/channel/playlist.m3u8"}]}`

**Comment by jaruba** [comment] 2022-12-31 21:02
@zoreu almost, you are still not following the documentation: https://github.com/Stremio/stremio-addon-sdk/blob/master/docs/api/responses/stream.md

which states:
> When using this property, you must also set stream.behaviorHints.notWebReady: true

**Comment by zoreu** [comment] 2022-12-31 21:23
> 

now i got it thanks

**Comment by IsraPerez98** [comment] 2023-03-06 08:03
Is it possible to do something similar for [defineSubtitlesHandler](https://github.com/Stremio/stremio-addon-sdk/blob/master/docs/api/requests/defineSubtitlesHandler.md) ?

I'm trying to build an addon but the URLs used to get the .srt files need a `Referer` header as well, I can't find a way to work around this

**Comment by jaruba** [comment] 2023-03-07 21:02
@IsraPerez98 it is possible with the local proxy addon, see: https://github.com/dexter21767/stremio-addic7ed/blob/5ee447d3176c96860266c191a8cfd852b038d9aa/addic7ed.js#L45

**Comment by IsraPerez98** [comment] 2023-03-09 00:05
@jaruba Thank you, where can I find the documentation for the proxy options?

**Comment by dexter21767-dev** [comment] 2023-03-14 11:46
> Is it possible to do something similar for [defineSubtitlesHandler](https://github.com/Stremio/stremio-addon-sdk/blob/master/docs/api/requests/defineSubtitlesHandler.md)?


as Jaruba said, you can use the local proxy:
 ```LocalServerURL/proxy/EncodedProxyHeader/path```

`LocalServerURL`: the URL to the local proxy server usually is `http://127.0.0.1:11470`, which it might not be, which is an issue.

`EncodedProxyHeader`: the encoded header properties are:  
                d=${BaseURL}
                &h=referer:${referer} // h stands for header and can probably take other parameters other than referer 
                all those variables should be URL encoded 

`path` is the path of the required file

so if I want to access `https://stremio.com/downloads` with the referer set to `https://stremio.com` it will look like this:
`http://127.0.0.1:11470/proxy/d=https%3A%2F%2Fstremio.com&h=referer:https%3A%2F%2Fstremio.com/downloads`

**Comment by dexter21767-dev** [comment] 2023-03-14 11:48
@IsraPerez98 and I would suggest opening a new issue if u have more problems.
hijacking a 4 years old issue wouldn't bring much help imo.
